# Basic site info
title:              "Yuhao Chen •••"
description:        "Idears, Technology and Researches"
keywords:           
logo_text:          "Yuhao Chen"
show_tagline:       true # edit file in /_includes/tagline.html
show_social_icons:  true # edit file in /_includes/social_links.html
og_locale:          "en_US"
cover:              # site image cover

# Site URL settings
url:                https://boan2014.github.io/ # main url
baseurl:            null # for gh-pages
enforce_ssl:        

# Site author info
author:
  name:             "Yuhao Chen"
  email:            boan11235@gmail.com
  github_username:  boan2014
  twitter_username: boan2014
  facebook_url:     https://www.facebook.com/boan2014  

# Disqus comment settings
disqus_enabled:     false
disqus_shortname:   

# GA
google_analytics_code: 

# Build settings
source:             ./
destination:        ./_site
permalink:          /:year/:title
markdown:           kramdown
highlighter:        rouge
timezone:           Asia/Kuala_Lumpur
exclude:            ["README.md", "LICENSE.md", "CHANGELOG.md"]

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/scss
  style:            compressed # expanded

gems:
  - jekyll-sitemap
